name: Maven Repository

debug: false

permissions:
  index: true
  view: false
  deploy: false

server:
  host: 0.0.0.0
  port: 8080

database:
  driver: sqlite
  dsn: data/data.db

repository:
  - release
  - snapshot
